### ISSUE TITLE
Laravel 5.5 - BotManCacheClear.php causing issues.

### ISSUE THREAD

**Issue by Sammyjo20** [botman/studio-addons#28]
When using ` composer install ` or ` composer update `, I'm getting the issue below:

`` Class BotMan\Studio\Console\Commands\BotManCacheClear contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Console\GeneratorCommand::getStub) ``

I've had a look at the BotManCacheClear.php class and found that if you change the class extension from Illuminate\Console\GeneratorCommand to Illuminate\Console\Command it works fine:

` class BotManCacheClear extends GeneratorCommand `

to:

` class BotManCacheClear extends Command `

**Comment by jogeshpi03** [comment]
@Sammyjo20 Yes, It has a compatibility issue with `Illuminate\Console\GeneratorCommand`. I have fixed the issue, but not able to put it on the master branch. Anyway

Please take a look on the updated **BotManCacheClear.php** file

`<?php

namespace BotMan\Studio\Console\Commands;

use Illuminate\Filesystem\Filesystem;
use Illuminate\Console\GeneratorCommand;

class BotManCacheClear extends GeneratorCommand
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'botman:cache:clear';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Remove all cached conversations.';

    /**
     * Create a new command instance.
     * 
     * @param Filesystem $files
     */
    public function __construct(Filesystem $files)
    {
        parent::__construct($files);
    }

    /**
     * Execute the console command.
     *
     * @param \Illuminate\Filesystem\Filesystem $files
     * @return mixed
     */
    public function handle()
    {
        $cacheFolder = storage_path('botman');

        if ($this->files->exists($cacheFolder)) {
            $this->files->cleanDirectory($cacheFolder);
        }

        $this->info('BotMan cache cleared!');
    }
}
`

**Comment by Sammyjo20** [comment]
Sweet, thanks! 🤓
