### ISSUE TITLE
Upgrade to Laravel 6

### ISSUE THREAD

**Issue by romanstingler** [botman/studio-addons#41]

**Comment by vesper8** [comment]
@mpociot Could you please add compatibility for Laravel 6? There are PRs for it.. it's a very small change

And since Laravel 7 is right around the corner perhaps you can add support for it too so you don't have to do this again in a month's time

Thank you

**Comment by jasontxf** [comment]
Has this project been abandoned? :( 
I'm not able to upgrade too.

**Comment by crynobone** [comment]
See #46 

Currently working on reviving the project. We need to nail down CI integrations before supporting new versions to avoid breaking everyone code.
