### ISSUE TITLE
Check if composer install was successful

### ISSUE THREAD

**Issue by mpociot** [botman/studio-addons#7]
When installing a BotMan driver using the artisan command, we need to check if an error occurs and tell the user.
Right now we're always showing a success message.

https://github.com/botman/studio-addons/blob/master/src/Console/Commands/BotManInstallDriver.php#L78

**Comment by thormeier** [comment]
Changed `run() ` to `mustRun()` according to https://symfony.com/doc/current/components/process.html. Also added `symfony/process` as dependency to have correct typehinting when checking out the project standalone, but if that dependency doesn't make any sense, I could remove that. :)
